### ISSUE TITLE
How is cpu usage reported?

### ISSUE THREAD

**Issue by jmcbee** [hbouvier/node-monitor#1]
Forgive me but I can't find the code that does that.
- vmstat - memory
- df - disk
- netstat - network

**Comment by hbouvier** [comment]
Hi,

I presume that you are working on a Windows PC. Otherwise, vmstat (or vm_stat on mac), df and netstat are part of the "standard" MacOS and Linux distributions.

On windows, I installed them through Cygwin (http://cygwin.com). But just to warn you, I only tested it on a Windows 2003 Server, that I do not have access anymore, two and a half years ago.

**Comment by jmcbee** [comment]
@hbouvier no I have a linux server. I'm just trying to find the lines of code which does the cpu usage reporting, hehe.

**Comment by hbouvier** [comment]
Take a peek at lib/linux/vmstats.js at the begining of the file, in the comments, you will see that at the end of the output of vmstat are the CPU colums (user, system and idle). The script use a regular expression to extract them.
